j2-health/design-system

- .storybook/main.ts
- .storybook/preview.tsx
- src/components/breadcrumb/Breadcrumb.stories.ts
- src/components/breadcrumb/Breadcrumb.tsx
- src/components/breadcrumb/index.tsx
- src/components/button/Button.stories.ts
- src/components/button/Button.tsx
- src/components/card/Card.stories.ts
- src/components/card/Card.tsx
- src/components/dropdown/Dropdown.stories.tsx
- src/components/dropdown/Dropdown.tsx
- src/components/dropdown/index.tsx
- src/components/radio/Radio.stories.tsx
- src/components/radio/Radio.tsx
- src/components/radio/index.tsx
- src/index.d.ts
[Jira link](https://j2health.atlassian.net/browse/MKT-497)
> MKT-497: Implement design system components that we will need for the landscape screen

- src/components/popover/Popover.stories.tsx
- src/components/popover/Popover.tsx
- src/components/popover/__tests__/__snapshots__/popover.test.tsx.snap
- src/components/popover/__tests__/popover.test.tsx
- src/components/popover/index.tsx
[Jira link](https://j2health.atlassian.net/browse/MKT-528)
[Ant.d link](https://ant.design/components/popover)
> MKT-528: Add Popover to design system

- package-lock.json
- package.json
- src/components/spinner/Spinner.stories.tsx
- src/components/spinner/Spinner.tsx
- src/index.d.ts
- src/svgs/ProgressCircle.svg
- vite.config.ts
[Jira link](https://j2health.atlassian.net/browse/MKT-531-ADD-SPINNER)
This does not have a phosphor icon attached to it so I just exported the svg from figma.
> MKT-531: ADD-SPINNER

- src/components/alert/Alert.tsx
[Figma](https://www.figma.com/design/f1pn07TS2qUyypB6thL4iB/J2-Health-Design-System-(ant.design-5.20)?node-id=413-15306)
> MKT-531: Update alert icons with colors

- src/components/spinner/index.tsx
> MKT-531 - Add spinner index

- src/components/barchart/BarChart.stories.tsx
- src/components/barchart/BarChart.tsx
[Jira link](https://j2health.atlassian.net/browse/MKT-532)
This PR allows no `max` to be passed into the components so that HC computes its own max.
> MKT-532: Build plans chart switch button

- src/components/table/Table.module.css
- src/components/table/Table.stories.tsx
- src/components/table/Table.tsx
- src/components/table/__tests__/__snapshots__/table.test.tsx.snap
[Jira link](https://j2health.atlassian.net/browse/MKT-534)
> MKT-534: Build entity vs plan table

- src/components/collapse/Collapse.tsx
[Jira link](https://j2health.atlassian.net/browse/MKT-641)
> MKT-641: Collapse Missing “borderless” option

- src/components/notification/Notification.css
- src/components/notification/index.tsx
- src/components/notification/useNotification.tsx
[Jira link](https://j2health.atlassian.net/browse/MKT-538)
> MKT-538: Update useNotification to support NID notifications + style updates

- .storybook/preview.tsx
- src/components/alert/Alert.stories.tsx
- src/components/alert/Alert.tsx
- src/components/alert/__tests__/__snapshots__/alert.test.tsx.snap
- src/components/alert/__tests__/alert.test.tsx
- src/components/button/Button.css
- src/components/button/Button.stories.tsx
- src/components/dropdown/Dropdown.stories.tsx
- src/components/popover/Popover.stories.tsx
- src/components/tooltip/Tooltip.stories.tsx
[Jira link](https://j2health.atlassian.net/browse/MKT-570)
> MKT-570: Design feedback on the design system

- src/components/alert/Alert.stories.tsx
[Jira link](https://j2health.atlassian.net/browse/MKT-570)
Hello darkness my old friend
> MKT-570: Restrict storybook to use only configured alerts

- src/appTheme.ts
- src/components/form/Form.stories.tsx
- src/components/form/Form.tsx
- src/components/form/index.ts
[Jira link](https://j2health.atlassian.net/browse/MKT-581)
* Removes margin bottom for form items so that they can be configured in app
> MKT-581: Extend Network selector section to Compare view

- src/components/form/Form.css
- src/components/form/Form.tsx
- src/components/navMenu/NavMenu.module.css
[Jira link](https://j2health.atlassian.net/browse/MKT-571)
> MKT-571: Design feedback on the landscape screen

- src/appTheme.ts
- src/components/rate/Rate.css
- src/components/rate/Rate.stories.tsx
- src/components/rate/Rate.tsx
- src/components/rate/__tests__/Rate.test.tsx
- src/components/rate/__tests__/__snapshots__/Rate.test.tsx.snap
- src/components/rate/index.tsx
[Jira link](https://j2health.atlassian.net/browse/MKT-582)
> MKT-582: Add Rate to Design System

- src/components/navMenu/NavMenu.tsx
[Jira link](https://j2health.atlassian.net/browse/MKT-586)
> MKT-586: Create Providers table (Overlap)

- src/components/table/Table.module.css
- src/components/table/Table.stories.tsx
[Jira link](https://j2health.atlassian.net/browse/MKT-659)
Before: 
After:
> MKT-659: Plan comparison card bugs

- src/components/vennDiagram/VennDiagram.tsx
[Jira link](https://j2health.atlassian.net/browse/MKT-584)
> MKT-584: Create "Providers by Plan" chart (Breadth)

- src/components/tabs/Tabs.tsx
[Jira link](https://j2health.atlassian.net/browse/MKT-667)
This should match what our expectations are about tabs anyway I believe
> MKT-667: Make unused antd tabs destroy themselves

- src/components/filterform/FilterField.tsx
[Jira link](https://j2health.atlassian.net/browse/MKT-588)
https://github.com/user-attachments/assets/581aa7c8-d667-4ec0-9f4f-476d4bc6fd75
> MKT-588: Implement composite filtering UI for Overlap - Address Feedback

- src/components/table/Table.module.css
[MKT-672](https://j2health.atlassian.net/browse/MKT-672)
For table consistency across the app 
[MKT-672]: https://j2health.atlassian.net/browse/MKT-672?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Global table heading coloring

- src/components/popover/Popover.module.css
- src/components/popover/Popover.stories.tsx
- src/components/popover/Popover.tsx
- src/stylesheets/index.css
[MKT-731](https://j2health.atlassian.net/browse/MKT-731)
Looks like this: 
or this 
[MKT-731]: https://j2health.atlassian.net/browse/MKT-731?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MKT-731: Design System: Update column selector to support scroll

- src/components/popover/Popover.module.css
[MKT-731](https://j2health.atlassian.net/browse/MKT-731)
Design feedback updates - can't have the scroll bar always visible but adjusted height for partially visible item and scroll is contained in the checkbox portion 
[MKT-731]: https://j2health.atlassian.net/browse/MKT-731?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MKT-731 Scrollable column management

- .storybook/main.ts
- src/components/listpopover/ListPopover.module.css
- src/components/listpopover/ListPopover.stories.tsx
- src/components/listpopover/ListPopover.tsx
[Jira link](https://j2health.atlassian.net/browse/MKT-769)
> MKT-769: Add categories to ListPopover

- src/components/skeleton/Skeleton.tsx
- src/components/table/Table.module.css
- src/components/table/Table.tsx
[Jira link](https://j2health.atlassian.net/browse/MKT-750)
> MKT-750: Explore - Plans Scorecard Table

- src/components/table/Table.module.css
[Jira link](https://j2health.atlassian.net/browse/MKT-716)
> MKT-716: Hide entire table header while loading

- src/components/popover/Popover.module.css
- src/components/popover/Popover.tsx
[Jira link](https://j2health.atlassian.net/browse/MKT-784)
> MKT-784: Explore - Prevent queries > 50 plans

- src/components/table/Table.module.css
- src/components/table/Table.stories.tsx
- src/components/table/Table.tsx
[Jira link](https://j2health.atlassian.net/browse/J2NM-3414)
> J2NM-3414: Add alternating row colors to Table

- src/components/switch/Switch.css
- src/components/switch/Switch.stories.tsx
- src/components/switch/Switch.tsx
- src/components/switch/index.tsx
[Jira link](https://j2health.atlassian.net/browse/J2NM-3310)
> J2NM-3310: 3e - Steps Component

- src/components/popover/Popover.module.css
- src/components/popover/Popover.stories.tsx
- src/components/popover/Popover.tsx
[Jira link](https://j2health.atlassian.net/browse/J2NM-3487)
I think if req padding sizes continue to grow we can add a more dynamic approach but I didn't want to update all popovers atm
> J2NM-3487: Design Feedback: 3c - 3f
